apiVersion: v1
entries:
  helm-django:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-07-09T00:24:31.238233764Z"
    description: A Helm chart for Kubernetes
    digest: a8575156c2b7d745a18f3ba620bbb9ae5799ab820d9f31770d11885a497683f7
    maintainers:
    - email: dev.toaster@gmail.com
      name: Jolene Engo
    name: helm-django
    type: application
    urls:
    - https://jengo.github.io/helm-charts/helm-django-0.5.9+8b571c6.tgz
    version: 0.5.9+8b571c6
generated: "2021-07-09T00:24:31.236307623Z"
